/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { ThreeElements } from '@react-three/fiber'

type GLTFResult = GLTF & {
  nodes: {
    Curve023: THREE.Mesh
    Curve023_1: THREE.Mesh
  }
  materials: {
    OUTER: THREE.MeshStandardMaterial
    INNER: THREE.MeshStandardMaterial
  }
}

export function Model(props: ThreeElements['group']) {
  const { nodes, materials } = useGLTF('/AUW LOGO V2.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[1.303, 2.13, -2.383]} rotation={[Math.PI / 2, 0, 0]} scale={196.601}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve023.geometry}
          material={materials.OUTER}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve023_1.geometry}
          material={materials.INNER}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/AUW LOGO V2.glb')
